//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TF.Language", typeof(Language).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backstrok.
        /// </summary>
        internal static string Backstrok {
            get {
                return ResourceManager.GetString("Backstrok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle.
        /// </summary>
        internal static string Bicycle {
            get {
                return ResourceManager.GetString("Bicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike.
        /// </summary>
        internal static string Bike {
            get {
                return ResourceManager.GetString("Bike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaststroke.
        /// </summary>
        internal static string Breaststroke {
            get {
                return ResourceManager.GetString("Breaststroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butterfly.
        /// </summary>
        internal static string Butterfly {
            get {
                return ResourceManager.GetString("Butterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save training.
        /// </summary>
        internal static string CouldntSave {
            get {
                return ResourceManager.GetString("CouldntSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycling.
        /// </summary>
        internal static string Cycling {
            get {
                return ResourceManager.GetString("Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this item?.
        /// </summary>
        internal static string DeleteAlert {
            get {
                return ResourceManager.GetString("DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string Exercises {
            get {
                return ResourceManager.GetString("Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freestyle.
        /// </summary>
        internal static string Freestyle {
            get {
                return ResourceManager.GetString("Freestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance is not acceptable.
        /// </summary>
        internal static string IncorrectDistance {
            get {
                return ResourceManager.GetString("IncorrectDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is not acceptable.
        /// </summary>
        internal static string IncorrectTime {
            get {
                return ResourceManager.GetString("IncorrectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of training not acceptable.
        /// </summary>
        internal static string IncorrectType {
            get {
                return ResourceManager.GetString("IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trainings.
        /// </summary>
        internal static string NumberOfTrainings {
            get {
                return ResourceManager.GetString("NumberOfTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string sec {
            get {
                return ResourceManager.GetString("sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming.
        /// </summary>
        internal static string Swimming {
            get {
                return ResourceManager.GetString("Swimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        internal static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training was succfully saved.
        /// </summary>
        internal static string TrainingSaved {
            get {
                return ResourceManager.GetString("TrainingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
