// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TF {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_uk {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_uk() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TF.Language.uk", typeof(Language_uk).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        internal static string Backstrok {
            get {
                return ResourceManager.GetString("Backstrok", resourceCulture);
            }
        }
        
        internal static string Bicycle {
            get {
                return ResourceManager.GetString("Bicycle", resourceCulture);
            }
        }
        
        internal static string Bike {
            get {
                return ResourceManager.GetString("Bike", resourceCulture);
            }
        }
        
        internal static string Breaststroke {
            get {
                return ResourceManager.GetString("Breaststroke", resourceCulture);
            }
        }
        
        internal static string Butterfly {
            get {
                return ResourceManager.GetString("Butterfly", resourceCulture);
            }
        }
        
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        internal static string CouldntSave {
            get {
                return ResourceManager.GetString("CouldntSave", resourceCulture);
            }
        }
        
        internal static string Cycling {
            get {
                return ResourceManager.GetString("Cycling", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        internal static string Exercises {
            get {
                return ResourceManager.GetString("Exercises", resourceCulture);
            }
        }
        
        internal static string Freestyle {
            get {
                return ResourceManager.GetString("Freestyle", resourceCulture);
            }
        }
        
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        internal static string IncorrectDistance {
            get {
                return ResourceManager.GetString("IncorrectDistance", resourceCulture);
            }
        }
        
        internal static string IncorrectTime {
            get {
                return ResourceManager.GetString("IncorrectTime", resourceCulture);
            }
        }
        
        internal static string IncorrectType {
            get {
                return ResourceManager.GetString("IncorrectType", resourceCulture);
            }
        }
        
        internal static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        internal static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        internal static string RunningExercises {
            get {
                return ResourceManager.GetString("RunningExercises", resourceCulture);
            }
        }
        
        internal static string SwimmingExercises {
            get {
                return ResourceManager.GetString("SwimmingExercises", resourceCulture);
            }
        }
        
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        internal static string sec {
            get {
                return ResourceManager.GetString("sec", resourceCulture);
            }
        }
        
        internal static string Swimming {
            get {
                return ResourceManager.GetString("Swimming", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        internal static string TrainingSaved {
            get {
                return ResourceManager.GetString("TrainingSaved", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        internal static string DeleteAlert {
            get {
                return ResourceManager.GetString("DeleteAlert", resourceCulture);
            }
        }
        
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string NumberOfTrainings {
            get {
                return ResourceManager.GetString("NumberOfTrainings", resourceCulture);
            }
        }
        
        internal static string Triathlon {
            get {
                return ResourceManager.GetString("Triathlon", resourceCulture);
            }
        }
        
        internal static string AddFeedback {
            get {
                return ResourceManager.GetString("AddFeedback", resourceCulture);
            }
        }
        
        internal static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        internal static string AddNewTraining {
            get {
                return ResourceManager.GetString("AddNewTraining", resourceCulture);
            }
        }
        
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        internal static string MyFeedbacks {
            get {
                return ResourceManager.GetString("MyFeedbacks", resourceCulture);
            }
        }
        
        internal static string MyGroups {
            get {
                return ResourceManager.GetString("MyGroups", resourceCulture);
            }
        }
        
        internal static string MyResults {
            get {
                return ResourceManager.GetString("MyResults", resourceCulture);
            }
        }
        
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        internal static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        internal static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        internal static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
        
        internal static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        internal static string LoginToAccount {
            get {
                return ResourceManager.GetString("LoginToAccount", resourceCulture);
            }
        }
        
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        internal static string ContinueWithoutLogging {
            get {
                return ResourceManager.GetString("ContinueWithoutLogging", resourceCulture);
            }
        }
        
        internal static string DataMayBeLost {
            get {
                return ResourceManager.GetString("DataMayBeLost", resourceCulture);
            }
        }
    }
}
